apiVersion: nvidia.com/v1
kind: ClusterPolicy
metadata:
  name: nvidia-cluster-policy
spec:
  operator:
    defaultRuntime: containerd

  daemonsets:
    rollingUpdate:
      maxUnavailable: "1"

  driver:
    enabled: true

  toolkit:
    enabled: true

  devicePlugin:
    enabled: true
    config:
      name: default

  dcgm:
    enabled: true

  dcgmExporter:
    enabled: true

  gfd:
    enabled: true

  nodeStatusExporter:
    enabled: true

  migManager:
    enabled: false
    config:
      name: default-mig-parted-config

  mig:
    strategy: none
